# Generated by Django 3.0.3 on 2020-02-28 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('update', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='amazonlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='AmazonItem',
        ),
        migrations.DeleteModel(
            name='AmazonList',
        ),
        migrations.AddField(
            model_name='product',
            name='connctedlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.ProductList'),
        ),
    ]
